labels = [
    "B-NAME",
    "B-OBJECTIVE",
    "B-EDUCATION_INSTITUTION",
    "B-EDUCATION_COURSE",
    "B-CERTIFICATION",
    "B-EXPERIENCE_ORGANIZATION",
    "B-EXPERIENCE_YEAR",
    "B-EXPERIENCE_DESIGNATION",
    "B-EDUCATION_YEAR",
    "B-CURRENT_LOCATION",
    "B-ACHIEVEMENTS",
    "B-SKILLS",
]
