labels = [
    "NAME",
    "OBJECTIVE",
    "EDUCATION_INSTITUTION",
    "EDUCATION_COURSE",
    "CERTIFICATION",
    "EXPERIENCE_ORGANIZATION",
    "EXPERIENCE_YEAR",
    "EXPERIENCE_DESIGNATION",
    "EDUCATION_YEAR",
    "CURRENT_LOCATION",
    "ACHIEVEMENTS",
    "SKILLS",
]
